### PR TITLE
Add tag deletion functionality. Already present on API

### PR DESCRIPTION
**Pull request by fernandodimperio**
# 🚀 Motivation (Why is this PR needed?)
The API has functionality to delete tags from jobs, the SDK don't.
This PR adds this functionality on the SDK.

# 🛠 Changes
Created a new method "delete_tags" to delete tags from jobs.
Target tags must be provided.
it can be filtered by batch_id if needed.

# 🧪 Testing

# Development Checklist

- [ ] Documentation
- [ ] Tests
- [ ] PR title with correct [format](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#-commit-message-format)?
- [ ] Is this a breaking change? If yes, include `BREAKING CHANGE` in your PR/commit [text](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit-message-footer).
 
# 🗒️ Release notes

### User-facing change?

- [ ] No. Skip the rest of this section.
- [ ] Yes. Complete the sections below to define what is included in the release notes for super.AI users.

### How should the PR be classified in the release notes? Choose one

- [ ] `Major new feature` - A new landmark feature that notably expands the product
- [ ] `New feature` - Any new functionality that is added
- [ ] `Bugfix` - Anything that corrects an error or unexpected behavior
- [ ] `Enhancement` - An improvement/change that was not a bugfix

### Short description of the change and how it benefits the user
Created a new method "delete_tags" to delete tags from jobs. This functionality already exists on the API but not on the SDK.
Target tags must be provided.
it can be filtered by batch_id if needed.

### Long description for major new features

(2+ sentences explaining what the feature is, why it's important, and how it benefits the user)

### CODE REVIEW

**Comment by lpfann** [comment]
Thanks for the changes.
Could you run the `black` formatter or pre-commit to fix the formatting?
The version of `black` is given here: https://github.com/mysuperai/superai-sdk/blob/main/.pre-commit-config.yaml

**Comment by fernandodimperio** [comment]
> Thanks for the changes. Could you run the `black` formatter or pre-commit to fix the formatting? The version of `black` is given here: https://github.com/mysuperai/superai-sdk/blob/main/.pre-commit-config.yaml

done :)

**Comment by lpfann** [comment]
> > Thanks for the changes. Could you run the `black` formatter or pre-commit to fix the formatting? The version of `black` is given here: https://github.com/mysuperai/superai-sdk/blob/main/.pre-commit-config.yaml
> 
> done :)

Could you merge the latest changes from `main` branch? One of your other additions is leading to merge conflicts.

**Comment by fernandodimperio** [comment]
Is this enough?

**Comment by lpfann** [comment]
> Is this enough?

There was still a `black` issue for some reason. 
You can locally run the same linting steps as the CI with [earthly](https://earthly.dev/get-earthly):
`earthly +linter` to debug it.

I fixed the issues now and updated the branch.

**Comment by lpfann** [comment]
Merged! Thanks for your contribution to this project @fernandodimperio 🎉

**Comment by fernandodimperio** [comment]
thanks for all the help on pushing things correctly.

have fun :)

**Pull request merged**
